<?php

/**
 * @file
 *
 */

/**
 * Implements hook_archimedes_alter().
 *
 * Adds additional checks for Archimedes.
 */
function fzarch_archimedes_alter(&$owl) {
  module_load_include('inc', 'fzarch');
  // Unstaged / uncommitted modifications in Git repos.
  if ($values = fzarch_git_status()) {
    $owl->createField('field_git_status', $values);
  }

  if ($info = fzarch_civicrm_gitinfo()) {
    $owl->createField('field_civicrm_git_commit', $info['commit_hash']);
    $owl->createField('field_civicrm_git_branch', $info['branch']);
  }
}

/**
 * Implements hook_archimedes_rows_alter().
 */
function fzarch_archimedes_rows_alter(&$rows, &$owl) {
  module_load_include('inc', 'fzarch');
  $civicrm_git_commit = (string) $owl->getField('field_civicrm_git_commit');
  if (!empty($civicrm_git_commit)) {
    $rows[] = array(t('CiviCRM Git Commit'), $civicrm_git_commit);
  }
  $civicrm_git_branch = (string) $owl->getField('field_civicrm_git_branch');
  if (!empty($civicrm_git_branch)) {
    $rows[] = array(t('CiviCRM Git Branch'), $civicrm_git_branch);
  }
  $git_status = (string) $owl->getField('field_git_status');
  if (!empty($git_status)) {
    $rows[] = array(array('data' => t('Git Status'), 'style' => 'vertical-align: top;'), $git_status);
  }
}
